- hosts: all
  port: 2222
  user: vagrant
  sudo: yes
  gather_facts: yes
  roles:
    - initial
    - redis
    - mysql
    - nginx
    - sentry
  handlers:
    - name: restart supervisord
      shell: systemctl restart supervisord.service
