---

- name: install yum mysql-repository
  yum: name={{ item }} state=installed
  with_items:
    - "{{ repository }}"

- name: install yum mysql
  yum: name={{ item }} state=latest
  with_items:
    - "{{ packages }}"

- name: copy my.cnf -> /etc/my.cnf
  action: template src=my.cnf dest=/etc/my.cnf
  # notify: 
  #   - start mysql
  #   - enable mysql

- name: systemctl restart mysqld
  shell: systemctl restart mysqld
- name: systemctl enable mysqld
  shell: systemctl enable mysqld

