- name: install yum mysql-repository
  yum: name={{ item }} state=installed
  with_items:
  - "{{ repository }}"

- name: install yum mysql
  yum: name={{ item }} state=latest
  with_items:
  - "{{ packages }}"

- name: copy my.cnf -> /etc/my.cnf
  template: src=my.cnf dest=/etc/my.cnf

- name: service mysqld start. chkconfig on
  service: name=mysqld state=running enabled=yes

#- name: Execute mysql_secure_installation
#  script: secure_install.sh ""
#  sudo: yes
#  ignore_errors: True

- name: set root account with password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"

- name: ~/.my.cnf を配置
  template:
    src: my.cnf.j2
    dest: "{{ lookup('env', 'HOME') }}/.my.cnf"
    mode: 0600