# Create a new database with name 'sentry'
- mysql_db: login_user=root login_password='' name=sentry encoding=utf8  state=present
- mysql_user: login_user=root login_password='' name=sentry password=sentry priv=sentry.*:ALL,GRANT state=present
